#!/usr/bin/env bash
# Uses a while loop to display Holberton School and uses
# if, elif, and else to print bad luck or good luck instead on lines 4 or 8
i="0"
while [ $i -lt 10 ]; do
    if [ $i -eq 3 ]
    then
	echo "bad luck"
    elif [ $i -eq 7 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    i=$((i+1))
done
